version: '3.8'
services:
  dev-db:
    image: postgres:12
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: wongames
      POSTGRES_USER: wongames
      POSTGRES_PASSWORD: wongames
    volumes:
      - ./data:/var/lib/postgresql/data